# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 608)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setMinimumSize(QtCore.QSize(485, 0))
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(70, 40, 70, 40)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableLayout = QtWidgets.QVBoxLayout()
        self.tableLayout.setContentsMargins(11, 11, 11, 11)
        self.tableLayout.setSpacing(6)
        self.tableLayout.setObjectName("tableLayout")
        self.title = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.tableLayout.addWidget(self.title)
        self.segmentTable = QtWidgets.QTableWidget(self.centralWidget)
        self.segmentTable.setMinimumSize(QtCore.QSize(0, 300))
        self.segmentTable.setObjectName("segmentTable")
        self.segmentTable.setColumnCount(2)
        self.segmentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.segmentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.segmentTable.setHorizontalHeaderItem(1, item)
        self.segmentTable.horizontalHeader().setCascadingSectionResizes(True)
        self.segmentTable.horizontalHeader().setDefaultSectionSize(80)
        self.segmentTable.horizontalHeader().setSortIndicatorShown(False)
        self.segmentTable.horizontalHeader().setStretchLastSection(True)
        self.segmentTable.verticalHeader().setVisible(True)
        self.segmentTable.verticalHeader().setCascadingSectionResizes(False)
        self.segmentTable.verticalHeader().setStretchLastSection(False)
        self.tableLayout.addWidget(self.segmentTable)
        self.verticalLayout_2.addLayout(self.tableLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeLabel = QtWidgets.QLabel(self.centralWidget)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.timeInput = QtWidgets.QLineEdit(self.centralWidget)
        self.timeInput.setObjectName("timeInput")
        self.verticalLayout.addWidget(self.timeInput)
        self.paceLabel = QtWidgets.QLabel(self.centralWidget)
        self.paceLabel.setObjectName("paceLabel")
        self.verticalLayout.addWidget(self.paceLabel)
        self.paceSelect = QtWidgets.QComboBox(self.centralWidget)
        self.paceSelect.setObjectName("paceSelect")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.verticalLayout.addWidget(self.paceSelect)
        self.addButton = QtWidgets.QPushButton(self.centralWidget)
        self.addButton.setEnabled(True)
        self.addButton.setMinimumSize(QtCore.QSize(0, 30))
        self.addButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.genButton = QtWidgets.QPushButton(self.centralWidget)
        self.genButton.setObjectName("genButton")
        self.verticalLayout.addWidget(self.genButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionNew_Workout = QtWidgets.QAction(MainWindow)
        self.actionNew_Workout.setObjectName("actionNew_Workout")
        self.actionOpen_Playlist = QtWidgets.QAction(MainWindow)
        self.actionOpen_Playlist.setObjectName("actionOpen_Playlist")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PaceTheMusic"))
        self.title.setText(_translate("MainWindow", "Playlist Segments"))
        item = self.segmentTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pace"))
        item = self.segmentTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Length (secs)"))
        self.timeLabel.setText(_translate("MainWindow", "Time"))
        self.paceLabel.setText(_translate("MainWindow", "Pace"))
        self.paceSelect.setItemText(0, _translate("MainWindow", "Slow"))
        self.paceSelect.setItemText(1, _translate("MainWindow", "Steady"))
        self.paceSelect.setItemText(2, _translate("MainWindow", "Fast"))
        self.paceSelect.setItemText(3, _translate("MainWindow", "Sprint"))
        self.addButton.setText(_translate("MainWindow", "Add Segment"))
        self.genButton.setText(_translate("MainWindow", "Generate Playlist"))
        self.actionNew_Workout.setText(_translate("MainWindow", "New Playlist"))
        self.actionOpen_Playlist.setText(_translate("MainWindow", "Open Playlist"))

