# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 379)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(171, 210, 241, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.inputLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.inputLayout.setContentsMargins(11, 11, 11, 11)
        self.inputLayout.setSpacing(6)
        self.inputLayout.setObjectName("inputLayout")
        self.timeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.timeLabel.setObjectName("timeLabel")
        self.inputLayout.addWidget(self.timeLabel, 0, 0, 1, 1)
        self.timeInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.timeInput.setObjectName("timeInput")
        self.inputLayout.addWidget(self.timeInput, 0, 1, 1, 1)
        self.paceLabel = QtWidgets.QLabel(self.layoutWidget)
        self.paceLabel.setObjectName("paceLabel")
        self.inputLayout.addWidget(self.paceLabel, 1, 0, 1, 1)
        self.paceSelect = QtWidgets.QComboBox(self.layoutWidget)
        self.paceSelect.setObjectName("paceSelect")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.inputLayout.addWidget(self.paceSelect, 1, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 20, 201, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.titleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.titleLayout.setContentsMargins(11, 11, 11, 11)
        self.titleLayout.setSpacing(6)
        self.titleLayout.setObjectName("titleLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.titleLayout.addWidget(self.title)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 270, 201, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.buttonLayout.setContentsMargins(11, 11, 11, 11)
        self.buttonLayout.setSpacing(6)
        self.buttonLayout.setObjectName("buttonLayout")
        self.addButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addButton.setEnabled(True)
        self.addButton.setObjectName("addButton")
        self.buttonLayout.addWidget(self.addButton)
        self.segmentTable = QtWidgets.QTableWidget(self.centralWidget)
        self.segmentTable.setGeometry(QtCore.QRect(210, 80, 201, 121))
        self.segmentTable.setObjectName("segmentTable")
        self.segmentTable.setColumnCount(2)
        self.segmentTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.segmentTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.segmentTable.setHorizontalHeaderItem(1, item)
        self.segmentTable.horizontalHeader().setCascadingSectionResizes(True)
        self.segmentTable.horizontalHeader().setSortIndicatorShown(False)
        self.segmentTable.horizontalHeader().setStretchLastSection(True)
        self.segmentTable.verticalHeader().setVisible(True)
        self.segmentTable.verticalHeader().setCascadingSectionResizes(False)
        self.segmentTable.verticalHeader().setStretchLastSection(False)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 631, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuPAce = QtWidgets.QMenu(self.menuBar)
        self.menuPAce.setObjectName("menuPAce")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew_Workout = QtWidgets.QAction(MainWindow)
        self.actionNew_Workout.setObjectName("actionNew_Workout")
        self.actionOpen_Playlist = QtWidgets.QAction(MainWindow)
        self.actionOpen_Playlist.setObjectName("actionOpen_Playlist")
        self.menuMenu.addAction(self.actionNew_Workout)
        self.menuMenu.addAction(self.actionOpen_Playlist)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuPAce.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PaceTheMusic"))
        self.timeLabel.setText(_translate("MainWindow", "Time:"))
        self.paceLabel.setText(_translate("MainWindow", "Pace:"))
        self.paceSelect.setItemText(0, _translate("MainWindow", "Slow"))
        self.paceSelect.setItemText(1, _translate("MainWindow", "Steady"))
        self.paceSelect.setItemText(2, _translate("MainWindow", "Fast"))
        self.paceSelect.setItemText(3, _translate("MainWindow", "Sprint"))
        self.title.setText(_translate("MainWindow", "Playlist Segments"))
        self.addButton.setText(_translate("MainWindow", "Add Segment"))
        item = self.segmentTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pace"))
        item = self.segmentTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Length (secs)"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuPAce.setTitle(_translate("MainWindow", "Pace"))
        self.actionNew_Workout.setText(_translate("MainWindow", "New Playlist"))
        self.actionOpen_Playlist.setText(_translate("MainWindow", "Open Playlist"))

