# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 361)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 147, 201, 54))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.segmentLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.segmentLayout.setContentsMargins(11, 11, 11, 11)
        self.segmentLayout.setSpacing(6)
        self.segmentLayout.setObjectName("segmentLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.segmentLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.segmentLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.segmentLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.segmentLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.delButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delButton.sizePolicy().hasHeightForWidth())
        self.delButton.setSizePolicy(sizePolicy)
        self.delButton.setMaximumSize(QtCore.QSize(21, 21))
        self.delButton.setObjectName("delButton")
        self.segmentLayout.addWidget(self.delButton, 0, 2, 1, 1)
        self.delButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delButton2.sizePolicy().hasHeightForWidth())
        self.delButton2.setSizePolicy(sizePolicy)
        self.delButton2.setMaximumSize(QtCore.QSize(21, 21))
        self.delButton2.setObjectName("delButton2")
        self.segmentLayout.addWidget(self.delButton2, 1, 2, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(171, 210, 241, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.inputLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.inputLayout.setContentsMargins(11, 11, 11, 11)
        self.inputLayout.setSpacing(6)
        self.inputLayout.setObjectName("inputLayout")
        self.timeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.timeLabel.setObjectName("timeLabel")
        self.inputLayout.addWidget(self.timeLabel, 0, 0, 1, 1)
        self.timeInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.timeInput.setObjectName("timeInput")
        self.inputLayout.addWidget(self.timeInput, 0, 1, 1, 1)
        self.paceLabel = QtWidgets.QLabel(self.layoutWidget)
        self.paceLabel.setObjectName("paceLabel")
        self.inputLayout.addWidget(self.paceLabel, 1, 0, 1, 1)
        self.paceSelect = QtWidgets.QComboBox(self.layoutWidget)
        self.paceSelect.setObjectName("paceSelect")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.paceSelect.addItem("")
        self.inputLayout.addWidget(self.paceSelect, 1, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 80, 201, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.titleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.titleLayout.setContentsMargins(11, 11, 11, 11)
        self.titleLayout.setSpacing(6)
        self.titleLayout.setObjectName("titleLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.titleLayout.addWidget(self.title)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 280, 201, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.buttonLayout.setContentsMargins(11, 11, 11, 11)
        self.buttonLayout.setSpacing(6)
        self.buttonLayout.setObjectName("buttonLayout")
        self.addButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addButton.setEnabled(True)
        self.addButton.setObjectName("addButton")
        self.buttonLayout.addWidget(self.addButton)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 631, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuPAce = QtWidgets.QMenu(self.menuBar)
        self.menuPAce.setObjectName("menuPAce")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew_Workout = QtWidgets.QAction(MainWindow)
        self.actionNew_Workout.setObjectName("actionNew_Workout")
        self.actionOpen_Playlist = QtWidgets.QAction(MainWindow)
        self.actionOpen_Playlist.setObjectName("actionOpen_Playlist")
        self.menuMenu.addAction(self.actionNew_Workout)
        self.menuMenu.addAction(self.actionOpen_Playlist)
        self.menuBar.addAction(self.menuMenu.menuAction())
        self.menuBar.addAction(self.menuPAce.menuAction())

        self.retranslateUi(MainWindow)
        self.delButton.clicked.connect(self.label_6.clear)
        self.delButton.clicked.connect(self.label_5.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PaceTheMusic"))
        self.label_5.setText(_translate("MainWindow", "60(sec)"))
        self.label_6.setText(_translate("MainWindow", "Slow "))
        self.label_4.setText(_translate("MainWindow", "Steady"))
        self.label_3.setText(_translate("MainWindow", "480(sec)"))
        self.delButton.setText(_translate("MainWindow", "X"))
        self.delButton2.setText(_translate("MainWindow", "X"))
        self.timeLabel.setText(_translate("MainWindow", "Time:"))
        self.paceLabel.setText(_translate("MainWindow", "Pace:"))
        self.paceSelect.setItemText(0, _translate("MainWindow", "Slow"))
        self.paceSelect.setItemText(1, _translate("MainWindow", "Steady"))
        self.paceSelect.setItemText(2, _translate("MainWindow", "Fast"))
        self.paceSelect.setItemText(3, _translate("MainWindow", "Sprint"))
        self.title.setText(_translate("MainWindow", "Playlist Segments"))
        self.addButton.setText(_translate("MainWindow", "Add Segment"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuPAce.setTitle(_translate("MainWindow", "Pace"))
        self.actionNew_Workout.setText(_translate("MainWindow", "New Playlist"))
        self.actionOpen_Playlist.setText(_translate("MainWindow", "Open Playlist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

